// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczxq2tQOVJ6XY__qHPQYU3TrnJDfRPVk',
    appId: '1:1019433960546:web:fbe6b49ee68c79fa70fd3b',
    messagingSenderId: '1019433960546',
    projectId: 'ss-duo',
    authDomain: 'ss-duo.firebaseapp.com',
    databaseURL: 'https://ss-duo-default-rtdb.firebaseio.com',
    storageBucket: 'ss-duo.firebasestorage.app',
    measurementId: 'G-XTHLT5NYPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8NLvXNyFVy-ChmI6syQKg-yyhNUbKud4',
    appId: '1:1019433960546:android:e33bd482f9faf97970fd3b',
    messagingSenderId: '1019433960546',
    projectId: 'ss-duo',
    databaseURL: 'https://ss-duo-default-rtdb.firebaseio.com',
    storageBucket: 'ss-duo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQA7iA1vvJiLw3wpgjReqjZpsTnvixw2o',
    appId: '1:1019433960546:ios:a805d837cd6eb7d070fd3b',
    messagingSenderId: '1019433960546',
    projectId: 'ss-duo',
    databaseURL: 'https://ss-duo-default-rtdb.firebaseio.com',
    storageBucket: 'ss-duo.firebasestorage.app',
    iosClientId: '1019433960546-rt0hkl1mk1umfv14ud5v0067pji07iee.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQA7iA1vvJiLw3wpgjReqjZpsTnvixw2o',
    appId: '1:1019433960546:ios:a805d837cd6eb7d070fd3b',
    messagingSenderId: '1019433960546',
    projectId: 'ss-duo',
    databaseURL: 'https://ss-duo-default-rtdb.firebaseio.com',
    storageBucket: 'ss-duo.firebasestorage.app',
    iosClientId: '1019433960546-rt0hkl1mk1umfv14ud5v0067pji07iee.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBczxq2tQOVJ6XY__qHPQYU3TrnJDfRPVk',
    appId: '1:1019433960546:web:a237f3e0a5c0989770fd3b',
    messagingSenderId: '1019433960546',
    projectId: 'ss-duo',
    authDomain: 'ss-duo.firebaseapp.com',
    databaseURL: 'https://ss-duo-default-rtdb.firebaseio.com',
    storageBucket: 'ss-duo.firebasestorage.app',
    measurementId: 'G-W4856LQ2BS',
  );
}
